name: Cron job to update kernel

on:
  push:
  
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:

jobs:
  Mainline:
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout Repo'
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: update.sh
        run: |
          ls -l
          id
          cat << EOF > entrypoint.sh
          cd /build
          ls -l
          id
          useradd builduser -m
          passwd -d builduser
          pacman -Syu --noconfirm --needed sudo pacman-contrib
          chown builduser:builduser * .
          sudo -u builduser ./update.sh
          EOF

          if docker run -t -v $PWD:/build archlinux /bin/bash /build/entrypoint.sh; then
            echo "publish=no" >> $GITHUB_ENV
            exit 0
          else
            echo "publish=yes" >> $GITHUB_ENV
            grep pkgver= PKGBUILD >> $GITHUB_ENV
            grep pkgrel= PKGBUILD >> $GITHUB_ENV
            grep pkgbase= PKGBUILD >> $GITHUB_ENV
          fi
      - name: Create PR
        if: ${{env.publish}} == 'yes'
        uses: peter-evans/create-pull-request@v4
        env:
          commit-message: ${{env.pkgbase}} v${{env.pkgver}}-${{env.pkgrel}}
          branch: create-pull-request/v${{env.pkgver}}-${{env.pkgrel}}
          delete-branch: true
          title: v${{env.pkgver}}-${{env.pkgrel}} Automatic update
